parameters:
- name: buildPlugins
  displayName: Build Plugins
  type: boolean
  default: true
- name: useNightly
  displayName: Use Nightly version number
  type: boolean
  default: false

variables:
  defines: 'NIGHTLY=$(Build.BuildNumber)'
  qtVersion: '5.15.2'

name: '$(Date:yyyy-MM-dd).$(Rev:r)'
jobs:
- job: Build

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      macos:
        imageName: 'macOS-10.15'
      macosx:
        imageName: 'macOS-10.15'
        qtVersion: '5.9.9'
        skipHardPlugins: 'true'
      win64:
        imageName: 'windows-2019'
        qtArch: 'win64_msvc2019_64'
      win32:
        imageName: 'windows-2019'
        qtArch: 'win32_msvc2019'

  pool:
    vmImage: $(imageName)

  steps:
  - bash: |
      echo '##vso[task.setvariable variable=MatrixName]'$(echo $(Agent.JobName) | cut -d' ' -f2)
      echo "##vso[task.setvariable variable=arch]$(qtArch)"
      if [ ${{ parameters.useNightly }} = True ]; then
        echo "##vso[task.setvariable variable=nightlyDefines]$(defines)"
        echo "##vso[task.setvariable variable=nightlyString]-nightly"
        echo "##vso[task.setvariable variable=buildNumString].$(Build.BuildNumber)"
      else
        echo "##vso[task.setvariable variable=nightlyDefines]"
        echo "##vso[task.setvariable variable=nightlyString]"
        echo "##vso[task.setvariable variable=buildNumString]"
      fi
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Set matrix env variables'

  - checkout: self

  - template: ci/install-qt.yml
    parameters:
      version: $(qtVersion)

  - pwsh: ci/pwsh/build.ps1
    displayName: 'Build qView'

  - ${{ if eq(parameters.buildPlugins, true) }}:
    - template: ci/plugins.yml

  - template: ci/deploy.yml

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'qView$(nightlyString)-$(MatrixName)$(buildNumString)'
    condition: and(succeeded(), ne(variables['dontPublish'], 'true'))
    displayName: 'Publish build artifact'

